spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: postgres # database username
        password: postgres # database password
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect


